### ISSUE TITLE
Carthage install not working

### ISSUE THREAD

**Issue by Biclops** [carambalabs/SugarRecord#259]
Here's my cartfile
github "pepibumur/sugarrecord"

This is what I get back
computerName:AppName user$ carthage update
*** Fetching sugarrecord
*** Fetching Result
Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD Library/ObjectMapper) but encountered: 
computerName:AppName user$ 

I'm new to Carthage but is something wrong with one of the submodules?

**Comment by jodyheavener** [comment]
I am also unable to install via Carthage. I just get `*** Fetching SugarRecord` and then it hangs forever.

**Comment by pepibumur** [comment]
Thanks for reporting it @jodyheavener and @Biclops .
I'll have a look

**Comment by TonnyTao** [comment]
@jodyheavener I suppose the SugarRecord project is too large.

git clone
Receiving objects:  30% (3169/10364), 39.18 MiB | 39.00 KiB/s

It's about 122.81M, it should takes much time to download it.

My solution is git clone it firstly, and then use a local project in Cartfile

**Comment by pepibumur** [comment]
Carthage support has been disabled in the last version.
