### ISSUE TITLE
Support to Swift 3

### ISSUE THREAD

**Issue by pepibumur** [carambalabs/SugarRecord#262]

**Comment by JackoPlane** [comment]
Is there any updates to timelines with becoming Xcode 8 beta 6 compatible?

**Comment by pepibumur** [comment]
We're working on it. We'll have the version ready soon.

**Comment by pepibumur** [comment]
Supported with SugarRecord 3.0
https://github.com/carambalabs/SugarRecord/releases/tag/3.0.0.alpha.1
