### ISSUE TITLE
Create targets without the Reactive dependency

### ISSUE THREAD

**Issue by dukemike** [carambalabs/SugarRecord#268]
Is there a recommended way to install SugarRecord without CocoaPods or Carthage? Dragging in the Xcode project and linking SugarRecordCoreDataFramework iOS appears to depend upon ReactiveCocoa. 

I would like to have the equivalent to `pod "SugarRecord/CoreData"`.

**Comment by pepibumur** [comment]
If you checkout the project and add it to your workspace you should be able to link your project against the library of the SugarRecord project. Could you try that and tell me if it works? Also feel free to contribute with the README updating it and adding the steps of *how to* do it. 😛

**Comment by dukemike** [comment]
Is the intent that the `SugarRecord-CoreData-iOS` target should require ReactiveCocoa? I had to change the target membership of several files to build without it. I can create another build target to make allow targets for with and without if you'd like.

**Comment by pepibumur** [comment]
The current targets are tied to Reactive libraries. I have plans to create targets that are reactive independent. This is actually how it's done with the CocoaPod setup.

**Comment by dukemike** [comment]
To build the SugarRecord-CoreData-iOS target without CocoaPods or Carthage, I:

* drug `SugarRecord.xcodeproj` into the project
* imported `UIKit` in `CoreDataObservable` to correct errors for indexPath.row
* updated the target dependencies for files under `SugarRecord/Source/Reactive` to exclude SugarRecord-CoreData-iOS
* unlink `RxSwift.framework`, `ReactiveCocoa.framework`, and `Result.framework` from the SugarRecord-CoreData-iOS target

Anything you'd like me to do? Would you like me to add it to the README?

**Comment by pepibumur** [comment]
Done @dukemike . Check out the last release https://github.com/carambalabs/SugarRecord/releases/tag/3.0.0-alpha.1

It supports Carthage without any reactive dependency.
