### ISSUE TITLE
I keep getting this "Realm accessed from incorrect thread"

### ISSUE THREAD

**Issue by sasikiran** [carambalabs/SugarRecord#271]
Hello,
 I've just started using this library. I am running into 
`libc++abi.dylib: terminating with uncaught exception of type realm::IncorrectThreadException: Realm accessed from incorrect thread.`

I tried calling my realm operations only from a main thread, but to no avail. 

```
func removeGotOffer(row: Int) {
        Async.main {
            let offerCode = self.offers[row].code
            try! self.db.operation({ (context, save) -> Void in
                guard let offer = try! context.request(Offer.self).filteredWith("code", equalTo: offerCode).fetch().first else {
                    debugPrint("Couldn't find the required offer to delete")
                    return
                }
                _ = try? context.remove(offer)
                save()
            })
        }
    }
```

**Comment by pepibumur** [comment]
Hi @sasikiran . I've detected a bug with the current implementation. Because it uses an already existing context that was created on a different thread. I'll fix it and push the fix as soon as possible.

**Comment by sasikiran** [comment]
Thanks!

**Comment by pepibumur** [comment]
@sasikiran could you try with the last version of SugarRecord?

**Comment by pepibumur** [comment]
Closing the issue, couldn't reproduce it and got no input from the user.

**Comment by M0TRIX** [comment]
is there some one has solved this problem ??

**Comment by M0TRIX** [comment]
@pepibumur  
@sasikiran
