### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by startupthekid** [carambalabs/SugarRecord#277]
In #259, you commented that Carthage support was disabled in the latest release. While I'm sure there's a good reason for it, that decision has cascading effects. Upgrading SugarRecord caused all of my CI builds to break because it could no longer be built manually which forced me to build the framework by hand and embedded it in each individual project. This is particularly bad when considering apps already in production where all the automation and build process suddenly started failing. It's easy to point to the older versions so no big deal, just wanted to make sure this becomes a feature in later releases. Is there a timeline as to when it will be re-enabled? If you need help, I'd be glad to code review anything.

**Comment by pepibumur** [comment]
@startupthekid . I'll work on it this week. You can still point to the previous version. It's the next big priority. I did a big cleanup in the project, removing all the reactive code and reorganizing the source code. With this working, I'll create the Carthage project again. Sorry for the inconveniences. I'll keep you posted. Are you using the Reactive layer of SugarRecord?

**Comment by startupthekid** [comment]
No worries, thanks for the quick response @pepibumur! I am, particularly the RxSwift.

**Comment by pepibumur** [comment]
I started with it here https://github.com/carambalabs/SugarRecord/pull/278 @startupthekid

**Comment by startupthekid** [comment]
Great choice of GIF!

**Comment by pepibumur** [comment]
@startupthekid can you try with this release https://github.com/carambalabs/SugarRecord/releases/tag/3.0.0.alpha.1. Notice that the support to Swift 2.3 has been dropped.
