### ISSUE TITLE
Multithreading Violation when using CoreData

### ISSUE THREAD

**Issue by v-ken** [carambalabs/SugarRecord#282]
When [Multi-Threading Assertions](https://oleb.net/blog/2014/06/core-data-concurrency-debugging/) is enabled, the debugger halts at `+[NSManagedObjectContext __Multithreading_Violation_AllThatIsLeftToUsIsHonor__]` when saving the context in:

```swift
public func operation<T>(operation: (context: Context, save: () -> Void) throws -> T) throws -> T
```

**Comment by v-ken** [comment]
Created a [pull request](https://github.com/carambalabs/SugarRecord/pull/283) which fixes this

**Comment by pepibumur** [comment]
Great, nice job @v-ken . Merging it!
