### ISSUE TITLE
RX Support removed

### ISSUE THREAD

**Issue by grangej** [carambalabs/SugarRecord#284]
I noticed we removed RX Support from latest release, what is the status of the modules for RX, i noticed they are pretty empty, is this something I can help with.

**Comment by pepibumur** [comment]
@grangej would be amazing if you could help with them. The idea is providing the reactive interface in extensions instead of the same repository. Would you like to help with that?

**Comment by grangej** [comment]
Yes I will take this up as soon as time allows!

**Comment by pepibumur** [comment]
Closing this issue for now. We don't plan to support any reactive interface in the short term.

**Comment by juliengdt** [comment]
why closing but asking for PR ? i don't understand

**Comment by pepibumur** [comment]
I've removed it because I think providing reactive interface shouldn't be in the scope of SugarRecord but as a part of another library that extends the interface. I'll create a new repository, something like `Rx+SugarRecord` that adds that reactive interface.
