### ISSUE TITLE
SugarRecord/CoreData 2.3.1 Swift 2.3 Xcode 8

### ISSUE THREAD

**Issue by jimpeters145** [carambalabs/SugarRecord#287]
## What
> Imported with cocoa pods.  2 compiler errors.

## Context
> CoreDataDefaultStorage line 183.  Value of optional type String? not unwrapped; did you mean to use! or ??

Store.Swift line 15.  Same error as above.

## Proposal
> I did a clone of the project ...  cannot build because 2 realm issues ...

**Comment by pepibumur** [comment]
Duplicated https://github.com/carambalabs/SugarRecord/issues/262
