### ISSUE TITLE
CocoaPod

### ISSUE THREAD

**Issue by slli** [carambalabs/SugarRecord#289]
Cannot install latest SugarRecord:
```
pod 'SugarRecord', :git => 'https://github.com/carambalabs/SugarRecord.git', :branch => 'master'
```

[!] Unable to satisfy the following requirements:

- `Realm (~> 1.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Realm (~> 1.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by pepibumur** [comment]
@slli try what the error says. Execute `pod repo update` first and then `pod update`.

**Comment by pepibumur** [comment]
@slli update your Podfile to use:

```
pod "SugarRecord", "3.0.0-alpha.1"
```
