### ISSUE TITLE
Errors in '3.0.0-alpha.1'

### ISSUE THREAD

**Issue by jimpeters145** [carambalabs/SugarRecord#292]
## What
>using pod 'SugarRecord/CoreData', '3.0.0-alpha.1', cleaned the project, set $(inherited) on build setting - Always Embed Swift Standard Libraries ...  errors in Result.swift and ResultProtocol.swift

## Context
> I had this fixed locally re. previously closed issue #287 

## Proposal
> Attach your own proposal *(if you have it)*. We'll discuss in on the issue to find the best one that fits into the library.

**Comment by pepibumur** [comment]
What error do you get @jimpeters145 ?

**Comment by karnett** [comment]
@pepibumur spec dependency appears to be pointing to the wrong version of Result.  It's pointing to the Swift 3 version, should be ..  spec.dependency "Result", "2.1.3"

**Comment by pepibumur** [comment]
Version `3.0.0-alpha.1` should point to the Result version with Swift 3.0 compatibility, shouldn't it? @karnett

**Comment by karnett** [comment]
is 3.0.0-alpha.1 using Swift 3.0? I thought that was using Swift 2.3. If that's the case, do you have a Swift 2.3 version?

**Comment by pepibumur** [comment]
Can you try with `2.3.1` @karnett ?
