### ISSUE TITLE
Carthage build error

### ISSUE THREAD

**Issue by kolisko** [carambalabs/SugarRecord#293]
I am trying build SR 3.0.0 using Carthage (Xcode8). 

### Here is my Cartfile

#github "pepibumur/sugarrecord"
github "pepibumur/sugarrecord" ~> 3.0.0

### The output of build

1 Michal-MBP:ewaycrm kolisko$ carthage update sugarrecord  --platform iOS
*** Fetching Eureka
*** Fetching SwiftyJSON
*** Fetching SwiftCSV
*** Fetching sugarrecord
*** Fetching CryptoSwift
*** Fetching SQLite.swift
*** Fetching Result
*** Downloading realm-cocoa.framework binary at "v1.0.1"
*** Checking out Result at "2.1.3"
*** Downloading ReactiveCocoa.framework binary at "v4.2"
*** Checking out RxSwift at "2.5.0"
*** Checking out sugarrecord at "remove"
*** xcodebuild output can be found in /var/folders/cw/kw49vrmn5nx8scdvskyd2rqw0000gn/T/carthage-xcodebuild.PWCdJC.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Skipped building sugarrecord due to the error:
Dependency "sugarrecord" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/pepibumur/sugarrecord/issues/new
*** Building scheme "RxBlocking-iOS" in Rx.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/Users/kolisko/xcode/ewaycrm/Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Users/kolisko/xcode/ewaycrm/Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
warning: no umbrella header found for target 'RxSwift-iOS', module map will not be generated
warning: no umbrella header found for target 'RxSwift-iOS', module map will not be generated
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/kolisko/xcode/ewaycrm/Carthage/Checkouts/RxSwift/Rx.xcworkspace -scheme RxBlocking-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
--- xcodebuild: WARNING: Unable to open project file '/Users/kolisko/xcode/ewaycrm/Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Users/kolisko/xcode/ewaycrm/Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by pepibumur** [comment]
Solved here https://github.com/carambalabs/SugarRecord/pull/295
