### ISSUE TITLE
Lower the iOS Deployment Target to 9.0 for the Carthage version of SugarRecord

### ISSUE THREAD

**Issue by thad** [carambalabs/SugarRecord#298]
## What
The iOS Deployment Target in the SugarRecord/Carthage Xcode project is currently set to version 9.3

## Context
I am using SugarRecord in a project that has a minimum iOS deployment target of 9.0.  Trying to use SugarRecord version 3.0 is now forcing me to change the deployment target of my project to match SugarRecord's. It looks like in the CocoaPods podspec you have a minimum iOS deployment target of iOS 8.0, so I don't understand why the Carthage version of the project would need to be any different. 

## Proposal
Would it be possible for you to change the minimum iOS deployment target to version 9.0 instead of 9.3? I don't know of any API changes that would require iOS 9.3 vs. 9.0, but please correct me if I'm wrong.

**Comment by pepibumur** [comment]
Sure it's possible. I'll do @thad . Feel free to propose a PR with the change.

**Comment by thad** [comment]
@pepibumur I'll create a PR, thanks!

**Comment by pepibumur** [comment]
Thanks! that would be great @thad

**Comment by pepibumur** [comment]
Done, thank you very much @thad
