### ISSUE TITLE
core data storage initialization - Module 'CoreData' has no member named 'Store'

### ISSUE THREAD

**Issue by kolisko** [carambalabs/SugarRecord#304]
When I use the initialization code from README got the error "Module 'CoreData' has no member named 'Store'

swift3, xcode8, sugarrecord 3.0.0

``` Swift
// Initializing CoreDataDefaultStorage
func coreDataStorage() -> CoreDataDefaultStorage {
    let store = CoreData.Store.Named("db")
    let bundle = NSBundle(forClass: self.classForCoder())
    let model = CoreData.ObjectModel.Merged([bundle])
    let defaultStorage = try! CoreDataDefaultStorage(store: store, model: model)
    return defaultStorage
}
```

**Comment by pepibumur** [comment]
@kolisko it should be lowercase with the Swift 3 changes. Would you like to change them and propose the changes as a PR?
Thanks!

**Comment by EPIKorial** [comment]
`    func coreDataStorage() -> CoreDataDefaultStorage {
        let store = CoreDataStore.named("db")
        let bundle = Bundle(for: self.classForCoder)
        let model = CoreDataObjectModel.merged([bundle])
        let defaultStorage = try! CoreDataDefaultStorage(store: store, model: model)
        return defaultStorage
    }`

Seems to be working

**Comment by crazypigs** [comment]
Where does the func coreDataStorage() -> CoreDataDefaultStorage {} ... go?

what is self.bundle. I can get it working but it looks like it isn't using the same core data store as the rest of my code which is not using sugarRecord
