### ISSUE TITLE
.contains(where: <#T##(RealmBasicEntity) throws -> Bool#>)

### ISSUE THREAD

**Issue by Ged2323** [carambalabs/SugarRecord#312]
## What
By any chance can you show an example of this using the entities in the database.

## Context
I've been trying to update entities though the only way I found was by deleting the old and adding the new.

Thanks in advance.

**Comment by pepibumur** [comment]
@Ged2323 there's an examples project that you can use as a reference. Please, let me know if that helps.

**Comment by Ged2323** [comment]
Hi Pedro,
 I had a search for contains in the MASTER example but couldn’t find anything.  Which examples are you referring to.  Thank you

**Comment by pepibumur** [comment]
https://github.com/carambalabs/SugarRecord/tree/master/Example
