### ISSUE TITLE
Can't retrieve object by id

### ISSUE THREAD

**Issue by woffle** [carambalabs/SugarRecord#315]
I may be missing something here but there is no way to fetch an object by NSManagedObject's objectID property.

I'm updating a model and trying to refresh stale data in the previous view controller.

**Comment by pepibumur** [comment]
@woffle you can pass a predicate where you specify the `objectID` that you are trying to fetch:

```objc
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"(self.objectID IN %@)", arrayOfObjectIDs];
```
