### ISSUE TITLE
There's no example project for CoreData+iCloud and document is wrong

### ISSUE THREAD

**Issue by Tom29** [carambalabs/SugarRecord#323]
- The document code is wrong, there is no `NSBundle` on Swift 3, it's `Bundle`
- `CoreData.ObjectModel.Merged([bundle])` ~> wrong syntax too. It might be `CoreDataObjectModel.merged([bundle])`
- And the last: there's no `iCloudConfig` method, i've found on the example project, and found nothing.

**Comment by pepibumur** [comment]
Hey @Tom29, thanks for reporting it. I've updated the `README.md` with the new syntax. You can check the changes here: https://github.com/carambalabs/SugarRecord/commit/214f34f9dc4eafd525af9a9cec5d5c6851bb0149
