### ISSUE TITLE
Cartfile still requires realm-cocoa 1.1.0 which doesn't build against Swift 3.1

### ISSUE THREAD

**Issue by kirmanie** [carambalabs/SugarRecord#327]
## What

SugarRecord no longer depends on realm-cocoa according to [this issue](https://github.com/carambalabs/SugarRecord/issues/324). But the Cartfile still requires realm-cocoa 1.1.0 which doesn't build against Swift 3.1.

## Proposal

Remove realm-cocoa 1.1.0 from Carfile.

**Comment by pepibumur** [comment]
Thanks for reporting it @kirmanie. I'll work on the fix

**Comment by kirmanie** [comment]
@pepibumur awesome!

**Comment by pepibumur** [comment]
@kirmanie  the support for Realm has been dropped in the last version. Realm interface is easy and straightforward that building a layer on top of it doesn't add much value. This layer keeps making sense for Core Data though. I've opened a PR removing the `Cartfile` and `Cartfile.resolved`. You can check it here:
https://github.com/carambalabs/SugarRecord/pull/329
