### ISSUE TITLE
Is it possible to delete all data (for example when user logs out) of core data? Not the models but data in the models

### ISSUE THREAD

**Issue by mabdullahsaeed** [carambalabs/SugarRecord#337]
Using SugarRecord with Swift 3. Is it possible to delete all data (for example when user logs out) of core data? Not the models/entities but data in the models/entities?

My SugarRecordManager.swift

      class SugarRecordManager
      {
      static let sharedInstance = SugarRecordManager()
       private init(){
        
       }
    
    // Initializing CoreDataDefaultStorage
    func coreDataStorage() -> CoreDataDefaultStorage {
        let store = CoreDataStore.named("db")
        let bundle = Bundle(for: type(of: self))
        let model = CoreDataObjectModel.merged([bundle])
        let defaultStorage = try! CoreDataDefaultStorage(store: store, model: model)
        return defaultStorage
    }

    // other functions for fetching and storing objects

    // want to write a function here to wipe out all data
    }

**Comment by pepibumur** [comment]
Hey @mabdullahsaeed, it's possible to delete all the data calling the method `removeStore()` on your storage. Let me know if that helps.
https://github.com/carambalabs/SugarRecord/blob/master/SugarRecord/Source/CoreData/Storages/CoreDataDefaultStorage.swift#L104
