### ISSUE TITLE
Extra Argument 'equalTo:' issue

### ISSUE THREAD

**Issue by jimijon** [carambalabs/SugarRecord#81]
Why won't this compile:

 if let extId:NSNumber = subJson["id"].number{

==> error here:    let category: Categorization? = Categorization.by("extID", equalTo: extId).find()?.first as Categorization?

**Comment by thewhitewood** [comment]
Seems to be back in version 1.0.5 and 1.0.6

`let objects = ObjectVO.by("value", equalTo: "false").find() as [ObjectVO]`

Gets the Error `Extra argument 'equalTo' in call`

**Comment by pepibumur** [comment]
@thewhitewood the result of find is not an array so you cannot cast that way. The return parameter is SugarRecordResults object which you can use as an array.

**Comment by thewhitewood** [comment]
That works for all objects but 

`let items:SugarRecordResults? = OxygenVO.all().sorted(by: sortDescriptor).find()`

but for

`let item = BodyPostureVO.by("id", equalTo: "00001")`

It is still causing the error

`Extra argument 'equalTo' in call`

thanks for your help on this

**Comment by pepibumur** [comment]
Because by doesn't imply fetch. The stack of calls should be
**.by() -> .sorted() -> .find()**
If you don't execute the find you are not executing any fetch to the database. I recommend you to take a look to the tests and example project where you have examples of fetching.

**Comment by thewhitewood** [comment]
Sorry - the code i put in wasnt complete...

Here's what we have...

`let items = BodyPostureVO.by("id", equalTo: value).sorted(by: sortDescriptor).find()`

**Comment by thewhitewood** [comment]
We've moved up from 1.0.3 and addressing the amends required

**Comment by thewhitewood** [comment]
It's ok - think I've got it - thanks for your help

**Comment by thewhitewood** [comment]
Looks like it only takes an NSString as the equalTo value - using String was causing the error ;)

All good now - thanks for getting back so quickly - appreciate the support you give us!

**Comment by pepibumur** [comment]
@thewhitewood could you leave a note about what it happened to you here: https://github.com/SugarRecord/SugarRecord/issues/88
We're dealing with it on that issue which is going to be covered soon.
Thanks for your report @thewhitewood
